# File: ~/.gemini/commands/ios-icons.toml
# Usage: /ios-icons <path-to-1024x1024-png-file>

description = "Generate all required iOS app icon sizes from a single 1024x1024 PNG file"

prompt = """
Please generate iOS app icons from the provided PNG file: {{args}}

Follow these steps:

1. Validate the input file exists and is a PNG format
2. Check that the image dimensions are 1024x1024 (or warn if different)  
3. Create an AppIcon.appiconset directory for the output
4. Generate all required iOS icon sizes using the macOS `sips` command:
   - iPhone: 20@2x, 20@3x, 29@2x, 29@3x, 40@2x, 40@3x, 60@2x, 60@3x
   - iPad: 20@1x, 20@2x, 29@1x, 29@2x, 40@1x, 40@2x, 76@1x, 76@2x, 83.5@2x
   - App Store: 1024@1x
5. Create a Contents.json file with proper Xcode asset catalog structure
6. Display a summary of generated files and usage instructions

Use this information about required sizes:
- Icon-20.png (20x20) - iPad 1x
- Icon-20@2x.png (40x40) - iPhone 2x, iPad 2x  
- Icon-20@3x.png (60x60) - iPhone 3x
- Icon-29.png (29x29) - iPad 1x
- Icon-29@2x.png (58x58) - iPhone 2x, iPad 2x
- Icon-29@3x.png (87x87) - iPhone 3x
- Icon-40.png (40x40) - iPad 1x
- Icon-40@2x.png (80x80) - iPhone 2x, iPad 2x
- Icon-40@3x.png (120x120) - iPhone 3x
- Icon-60@2x.png (120x120) - iPhone 2x
- Icon-60@3x.png (180x180) - iPhone 3x
- Icon-76.png (76x76) - iPad 1x
- Icon-76@2x.png (152x152) - iPad 2x
- Icon-83.5@2x.png (167x167) - iPad Pro 2x
- Icon-1024.png (1024x1024) - App Store

Example sips commands to resize images:
!{sips -Z 40 "{{args}}" --out "AppIcon.appiconset/Icon-20@2x.png"}
!{sips -Z 60 "{{args}}" --out "AppIcon.appiconset/Icon-20@3x.png"}

Remember to use the Shell tool with `sips` commands for all image processing tasks.
"""